apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: multistage-build-and-cache
build:
  artifacts:
    - image: builder
      context: .
      docker:
        dockerfile: Dockerfile
        target: builder
        cacheFrom:
          - builder
        buildArgs:
          BUILDKIT_INLINE_CACHE: "1"
    - image: app
      context: .
      requires:
        - image: builder
          alias: BUILDER
      docker:
        dockerfile: Dockerfile
  local:
    useBuildkit: true
  # tagPolicy:
  #   gitCommit:
  #     ignoreChanges: true
  tagPolicy:
    dateTime:
      format: 2006-01-02_15-04-05.999_MST